apiVersion: v1
kind: Service
metadata:
  name: ibak-pzoo
spec:
  ports:
  - port: 2888
    name: peer
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: ibak-zookeeper
    storage: persistent
